# Generated by Django 4.1.7 on 2023-04-09 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 4, 9, 20, 26, 3, 365137)),
        ),
    ]
